Auth
OpSurvey/BackEnd pull request #1
Opened 2022-09-20 17:49 UTC by ErnestoGarSa

I´ve updated the models, usecases and routes, changed the language messages to Spanish, changed the jwt token expiration to seven days.

2022-09-21 01:45 UTC, devCharles requested changes

2022-09-21 01:45 UTC, devCharles commented on src/models/quote-recipes.model.js
> +    },
Este deberia ser requerido tambien

2022-09-21 01:45 UTC, devCharles commented on src/models/quote-recipes.model.js
>          ref: "recipes"
Este tambien deberia ser requerido

2022-09-21 01:45 UTC, devCharles commented on src/models/quote.model.js
>      },
quoterId también debe ser requerido, no puede existir un quote sin quoter

2022-09-21 01:45 UTC, devCharles commented on src/models/recipe-materials.model.js
> +    },
Tambien debe ser requerido, no puede existir un recipe-materil si no hay recipeId

2022-09-21 01:45 UTC, devCharles commented on src/models/recipe-materials.model.js
>          ref: "materials"
Tambien debe ser requerido, no puede existir un recipe-materil si no hay materialId

2022-09-21 07:25 UTC, devCharles requested changes

2022-09-21 07:25 UTC, devCharles commented on src/usecases/quote-recipe.usecase.js
> +    // console.log("recipeId", recipeId)
Borremos el código que no usamos para mantener todo limpio

2022-09-21 07:25 UTC, devCharles commented on src/usecases/recipe-materials.usecase.js
> +    // console.log("recipeId", recipeId)
Tampoco esto es necesario

2022-09-23 18:06 UTC, ErnestoGarSa commented on src/usecases/recipe-materials.usecase.js
> +    // console.log("recipeId", recipeId)
Ya quedaron todos los cambios hechos

2022-09-23 18:15 UTC, closed without merging